#define IDI_ICON1                       101
#define IDS_APP_TITLE                   102
#define IDS_APP_DESCRIPTION             103
#define IDS_APP_TITLE_ZH               104
#define IDS_APP_DESCRIPTION_ZH         105
#define IDM_EXIT                        1001
#define IDM_SETTINGS                    1002
#define IDM_ABOUT                       1003
#define IDM_LANGUAGE_ZH                 1004
#define IDM_LANGUAGE_EN                 1005
#define IDM_AUTO_RECONNECT              1006