name: Build

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
    - name: Build
      run: msbuild "AudioPlaybackConnector-new.vcxproj" "-p:Configuration=Release;Platform=x64;Restore=true"
      shell: powershell
    - name: List files
      run: dir -Recurse | Select-String "AudioPlaybackConnector-new.exe"
      shell: powershell
    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector
        path: "**/AudioPlaybackConnector-new.exe"
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: false
        files: "**/AudioPlaybackConnector-new.exe"
